version: '3.4'

services:
  movieapiservice:
    image: ${DOCKER_REGISTRY-}movieapiservice
    build:
      context: .
      dockerfile: Day 006/MovieApiService/Dockerfile
    networks:
      movieservice.network:

  # MovieService: Database
  movieservice.db:
    image: mongo:latest
    hostname : movieservice.db
    container_name : movieservice.db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypass
    networks:
      movieservice.network:
    ports:
      - "27017:27017"
    volumes:
         - movieservice.db.volume:/data/db

  # MovieService: Database Management Tool
  mongo-express:
    image: mongo-express
    hostname: common.mongoexpress
    container_name: common.mongoexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
      # ME_CONFIG_MONGODB_URL: mongodb://root:mypass@nt:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_SERVER: movieservice.db  # MongoDB service name
      ME_CONFIG_MONGODB_PORT: 27017  # MongoDB port
    networks:
      movieservice.network:
    depends_on:
      - movieservice.db
networks:
  movieservice.network:
   driver: bridge
volumes:
  movieservice.db.volume:
    name: "movieservice.db.volume"
