version: '3.4'

services:
  saga.services.inventoryservice:
    image: ${DOCKER_REGISTRY-}sagaservicesinventoryservice
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
      - 8080:80
      - 9000:443

  saga.services.orderservice:
    image: ${DOCKER_REGISTRY-}sagaservicesorderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - 8081:80
      - 9001:443


  saga.services.paymentservice:
    image: ${DOCKER_REGISTRY-}sagaservicespaymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    ports:
      - 8082:80
      - 9002:443

  saga.demo.rabbitmq:
    image: "rabbitmq:3.10.6-management-alpine"
    hostname: "sagademo"
    ports:
      - 5672:5672
      - 15672:15672

    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}

