version: '3'
services:
  sftp:
    build: .
    container_name: sftp-server
    ports:
      - "2222:22"
    volumes:
      - ./data:/home/sftpuser/upload  # Local 'data' directory mapped to 'upload' directory in container
    restart: always
