version: '3.4'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    volumes:
      - ./localstorage/data:/data
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
    ports:
      - "10000:10000"
      - "10001:10001"
